################################################################
#
# MajnAuction plugin config file
#
################################################################

debug: false
custom-sign-text: '[MajnAuction]'

mysql:
  host: 'localhost'
  port: '3306'
  database: 'minecraft'
  user: 'MajnAuction'
  password: 'haha'

